#!/bin/bash

echo -n "$2: "

egrep -o '[^[:alnum:]_]CONFIG_[[:alnum:]_]*' "$1" | uniq | \
	awk -- '{ \
		s = substr($0, 9); \
		gsub("_", "/", s); \
		s = tolower(s); \
		printf "include/config/%s.h ", s; \
	}'

echo

if echo "$2" |  grep -q '\.h$'; then
	echo -e \\t@touch "$2"
fi
